name: documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Build Sphinx docs
        run: |
          hatch run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
